Update spec so title includes date

diff --git a/.github/workflows/issue-recorder.yml b/.github/workflows/issue-recorder.yml
--- a/.github/workflows/issue-recorder.yml
+++ b/.github/workflows/issue-recorder.yml
@@ -22,21 +22,51 @@ jobs:
             exit 1
           fi
 
-      # "start-blog_ブログはじめました" => "start-blog"
+      # "2025-06-16_start-blog_ブログはじめました" => "2025"
+      - name: Get year
+        run: |
+          YEAR=$(awk -F '[-_]' '{print $1}' <<< "${{ github.event.issue.title }}")
+          if [ "$YEAR" = "" ] || [ "$(echo "$YEAR" | grep -cE '^[0-9]{4}$')" -eq 0 ]; then
+            echo "ERROR: YEAR is empty or invalid" >&2
+            exit 1
+          else
+            echo "YEAR=$YEAR" >> $GITHUB_ENV
+          fi
+      # "2025-06-16_start-blog_ブログはじめました" => "06"
+      - name: Get month
+        run: |
+          MONTH=$(awk -F '[-_]' '{print $2}' <<< "${{ github.event.issue.title }}")
+          if [ "$MONTH" = "" ] || [ "$(echo "$MONTH" | grep -cE '^[0-9]{2}$')" -eq 0 ]; then
+            echo "ERROR: MONTH is empty or invalid" >&2
+            exit 1
+          else
+            echo "MONTH=$MONTH" >> $GITHUB_ENV
+          fi
+      # "2025-06-16_start-blog_ブログはじめました" => "16"
+      - name: Get day
+        run: |
+          DAY=$(awk -F '[-_]' '{print $3}' <<< "${{ github.event.issue.title }}")
+          if [ "$DAY" = "" ] || [ "$(echo "$DAY" | grep -cE '^[0-9]{2}$')" -eq 0 ]; then
+            echo "ERROR: DAY is empty or invalid" >&2
+            exit 1
+          else
+            echo "DAY=$DAY" >> $GITHUB_ENV
+          fi
+      # "2025-06-16_start-blog_ブログはじめました" => "start-blog"
       - name: Get slug
         run: |
-          SLUG=$(cut -d '_' -f1 <<< "${{ github.event.issue.title }}")
-          if [ "$SLUG" = "" ] || [ "$(echo "$SLUG" | grep -cE '^[A-Za-z0-9-]+$')" -eq 0 ]; then
+          SLUG=$(cut -d '_' -f2 <<< "${{ github.event.issue.title }}")
+          if [ "$SLUG" = "" ] || [ "$(echo "$SLUG" | grep -cE '^[A-Za-z0-9]+(-[A-Za-z0-9]+)*$')" -eq 0 ]; then
             echo "ERROR: SLUG is empty or invalid" >&2
             exit 1
           else
             echo "SLUG=$SLUG" >> $GITHUB_ENV
           fi
-      # "start-blog_ブログはじめました" => "ブログはじめました"
+      # "2025-06-16_start-blog_ブログはじめました" => "ブログはじめました"
       - name: Get title
         run: |
-          TITLE=$(cut -d '_' -f2 <<< "${{ github.event.issue.title }}")
-          if [ "$TITLE" = "" ]; then
+          TITLE=$(cut -d '_' -f3 <<< "${{ github.event.issue.title }}")
+          if [ "$TITLE" = "" ] || [ "$(echo "$TITLE" | grep -cE '^[^_]+$')" -eq 0 ]; then
             echo "ERROR: TITLE is empty or invalid" >&2
             exit 1
           else
@@ -52,21 +82,6 @@ jobs:
           else
             echo "MODE=file, issue" >> $GITHUB_ENV
           fi
-
-      # "2025-06-16"
-      - name: Get diary title
-        run: echo "DIARY_TITLE=$(gh issue list --repo "noraworld/reserved-diary" --limit 1 | awk '{ print $3 }')" >> $GITHUB_ENV
-        env:
-          GH_TOKEN: ${{ secrets.GH_TOKEN }}
-      # "2025-06-16" => "2025"
-      - name: Get year
-        run: echo "YEAR=$(cut -d '-' -f1 <<< ${{ env.DIARY_TITLE }})" >> $GITHUB_ENV
-      # "2025-06-16" => "06"
-      - name: Get month
-        run: echo "MONTH=$(cut -d '-' -f2 <<< ${{ env.DIARY_TITLE }})" >> $GITHUB_ENV
-      # "2025-06-16" => "16"
-      - name: Get day
-        run: echo "DAY=$(cut -d '-' -f3 <<< ${{ env.DIARY_TITLE }})" >> $GITHUB_ENV
 
       - name: Delete unnecessary labels
         run: |
